### ISSUE TITLE
Workflow doesn't work anymore

### ISSUE THREAD

**Issue by youngpilot** [wkoffel/alfred-amazon-affiliate-links#2]
Doesn't work anymore using the most recent Alfred & macOS Version

**Comment by wkoffel** [comment]
Thanks @youngpilot .  Yes, I needed to rebuild my more popular workflow alfred-terminal-control, I most likely need to do the same with this one.  I'll put it on my list to bump the rev and note here when I do.  Might take a week+ just based on my own schedule here.

**Comment by wkoffel** [comment]
Well, I guess technically I was accurate with my estimate of a "week+".  Alas, not very precise.  But the workflow is now updated to v1.1 with macOS 10.13 support.  Download the new version from https://cl.ly/331r1Z0B2z30 or from the dist directory in this repo.
